#-------------------------------
# General Site Settings

menu:
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

contact: >

  # Contact
  Lo puede encontrar al frente de la facultad de ciencias computacionales de la universidad de Guayaquil

#-------------------------------
# Work Section

projects:
- {name: 'Empanadas de queso', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Empandas Mixtas', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Empanadas hawaianas', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Emapanadaas rancheras', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Empanadas de carne', folder: 'proj-5', file: 'projects/proj-5.html'}
- {name: 'Empanadad de pollo', folder: 'proj-6', file: 'projects/proj-6.html'}
- {name: 'Empanadas de pizza', folder: 'proj-7', file: 'projects/proj-7.html'}
- {name: 'Empanadas mexicanas', folder: 'proj-8', file: 'projects/proj-8.html'}

#-------------------------------
# Contact Section

social:
- {name: 'facebook', link: 'https://www.facebook.com/pg/LasEmpanadasDeChicho/about/?ref=page_internal', icon: 'fab fa-facebook-square'}
# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
