#-------------------------------
# General Site Settings

menu:
- {name: 'Menu', url: 'https://cristopher-gomez-m.github.io/afk/'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # Portfolio Jekyll Theme

  This is a personal portfolio theme that I built from the ground up, using the [DevTips Starter Kit](http://devtipsstarterkit.com/) as a foundation for starting, and following closely the amazing tutorial by [Travis Neilson over at DevTips](https://www.youtube.com/watch?v=T6jKLsxbFg4&list=PL0CB3OvPhDA_STygmp3sDenx3UpdOMk7P). You can [check out the demo](lenpaul.github.io/portfolio-jekyll-theme/), and [fork the repository](https://github.com/LeNPaul/portfolio-jekyll-theme/fork), to get started.

contact: >
  # Contact

  Lo puede encontrar al frente de la facultad de ciencias computacionales de la universidad de Guayaquil
  <a href=”https://www.google.com/maps/place/Edificio+Torres+de+La+Merced/@-2.1903656,-79.8818191,19z/data=!3m1!4b1!4m5!3m4!1s0x902d6e78c08f947b:0x5882ae0ad1330363!8m2!3d-2.1903656!4d-79.8812706?hl=es”>Empanadas_de_Chicho</a>

#-------------------------------
# Work Section

projects:
- {name: 'Empanadas de queso', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Empandas Mixtas', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Empanadas hawaianas', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Emapanadaas rancheras', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Empanadas de carne', folder: 'proj-5', file: 'projects/proj-5.html'}
- {name: 'Empanadad de pollo', folder: 'proj-6', file: 'projects/proj-6.html'}
- {name: 'Empanadas de pizza', folder: 'proj-7', file: 'projects/proj-7.html'}
- {name: 'Empanadas mexicanas', folder: 'proj-8', file: 'projects/proj-8.html'}

#-------------------------------
# Contact Section

social:
- {name: 'facebook', link: 'https://www.facebook.com/pg/LasEmpanadasDeChicho/about/?ref=page_internal', icon: 'fab fa-facebook-square'}
# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
